version: 0.2

phases:
  install:
    commands:
      - pip3 install -r airflow_deploy/requirements.txt
  pre_build:
    commands:
      - echo running flake8 test
      - flake8 airflow_deploy/flake_test.py  
    on-failure: ABORT
  build:
    commands:
      - echo deploying to airflow
  post_build:
    commands:
      - echo deployment completed on `date`
