version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing venv...
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r airflow_deploy/requirements.txt
  build:
    commands:
      - echo deploying to airflow
  post_build:
    commands:
      - echo deployment completed on `date`
