version: 0.2

phases:
  install:
    commands:
      - pip3 install -r airflow_deploy/requirements.txt
  pre_build:
    commands:
      - echo running flake8 test
      - flake8 airflow_deploy/flake_test.py  
    on-failure: ABORT
  build:
    commands:
      - echo deploying to airflow
  post_build:
    commands:
      - aws ssm get-parameter --name KUMARTEST --with-decryption --query Parameter.Value --output text > ~/.ssh/airflow_dev.pem
      - chmod 600 ~/.ssh/airflow_dev.pem
      - scp -o StrictHostKeyChecking=no -i ~/.ssh/airflow_dev.pem  airflow_deploy/flake_test.py airflow@10.74.196.116:/home/airflow/
      - echo deployment completed on `date`
