version: 0.2

phases:
  install:
    commands:
      - pip3 install -r databricks_deploy/requirements.txt
  pre_build:
    commands:
      - echo running flake8 test
      - flake8 databricks_deploy/flake_test.py  
    on-failure: ABORT
  build:
    commands:
      - echo building databricks project
  post_build:
    commands:
      - echo databricks deployment completed on `date`
